### ISSUE TITLE
any comments in config line are ignored.

### ISSUE THREAD

**Issue by ghost** [pgnuta/juniper-config-to-set#1]
any comment (##) that is in the config is ignored even if its at the end of the line, so say you have a config line like this (some parts redacted):

system {
    host-name redacted;
    domain-name redacted.com;
    time-zone GMT;
    root-authentication {
        encrypted-password "redacted"; ## SECRET-DATA
    }

so your output WONT include the encrypted-password line or any line that has ## towards the end. been a number of years since i messed with php and havent looked at the php code yet.

could you fix this please?

**Comment by pgnuta** [comment]
Yeah i'll take a look at it.

**Comment by pgnuta** [comment]
New commit should fix this issue.  Removes the inline comment from the line before evaluation.
